"""拓竹官方配色预设 —— 全系 Hex Code Table（官方 PDF），official=True。

数据来源：us.store.bambulab.com 各商品页「Hex Code」链接的官方 PDF
（cdn.shopify.com/.../Bambu_<系列>_Hex_Code.pdf），2026-09-19 由
scripts 外的离线构建脚本从 PDF 解析生成，勿手改排序。
已有中文对照沿用旧表；新色名人工/词素翻译，en 保留官方英文名。
"""

def _co(name: str, en: str, hex_value: str) -> dict:
    return {"name": name or en, "en": en, "hex": hex_value, "official": True}

BAMBU_SERIES: dict[str, list[dict]] = {
    'ABS': [
    _co('白色', 'White', '#FFFFFF'),
    _co('拓竹绿', 'Bambu Green', '#00AE42'),
    _co('橄榄绿', 'Olive', '#789D4A'),
    _co('天蓝色', 'Azure', '#489FDF'),
    _co('宝蓝', 'Navy Blue', '#0C2340'),
    _co('蓝色', 'Blue', '#0A2CA5'),
    _co('橘黄色', 'Tangerine Yellow', '#FFC72C'),
    _co('橙色', 'Orange', '#FF6A13'),
    _co('红色', 'Red', '#D32941'),
    _co('紫色', 'Purple', '#AF1685'),
    _co('银色', 'Silver', '#87909A'),
    _co('黑色', 'Black', '#000000'),
    ],
    'ABS-GF': [
    _co('白色', 'White', '#FFFFFF'),
    _co('灰色', 'Gray', '#C6C6C6'),
    _co('橙色', 'Orange', '#F48438'),
    _co('红色', 'Red', '#E83100'),
    _co('蓝色', 'Blue', '#0C3B95'),
    _co('黑色', 'Black', '#000000'),
    ],
    'ASA': [
    _co('白色', 'White', '#FFFAF2'),
    _co('灰色', 'Gray', '#8A949E'),
    _co('红色', 'Red', '#E02928'),
    _co('绿色', 'Green', '#00A6A0'),
    _co('蓝色', 'Blue', '#2140B4'),
    _co('黑色', 'Black', '#000000'),
    ],
    'ASA Aero': [
    _co('白色', 'White', '#F5F1DD'),
    ],
    'ASA-CF': [
    _co('黑色', 'Black', '#000000'),
    ],
    'PAHT-CF': [
    _co('黑色', 'Black', '#1F1F1F'),
    ],
    'PC': [
    _co('白色', 'White', '#FFFFFF'),
    _co('透明黑', 'Clear Black', '#686865'),
    _co('黑色', 'Black', '#000000'),
    ],
    'PET-CF': [
    _co('黑色', 'Black', '#000000'),
    ],
    'PETG Basic': [
    _co('红色', 'Red', '#D6001C'),
    _co('橙色', 'Orange', '#FF671F'),
    _co('黄色', 'Yellow', '#FCE300'),
    _co('群青蓝', 'Reflex Blue', '#001489'),
    _co('宝蓝', 'Navy Blue', '#0086D6'),
    _co('雾蓝', 'Misty Blue', '#688197'),
    _co('绿色', 'Green', '#009639'),
    _co('松绿', 'Pine Green', '#034638'),
    _co('深棕', 'Dark Brown', '#4F2C1D'),
    _co('深米色', 'Dark Beige', '#DBC8B6'),
    _co('黑色', 'Black', '#000000'),
    _co('灰色', 'Gray', '#7F7E83'),
    _co('白色', 'White', '#FFFFFF'),
    ],
    'PETG HF': [
    _co('白色', 'White', '#FFFFFF'),
    _co('奶油色', 'Cream', '#F9DFB9'),
    _co('黄色', 'Yellow', '#FFD00B'),
    _co('橙色', 'Orange', '#F75403'),
    _co('红色', 'Red', '#EB3A3A'),
    _co('青柠绿', 'Lime Green', '#6EE53C'),
    _co('绿色', 'Green', '#00AE42'),
    _co('森林绿', 'Forest Green', '#39541A'),
    _co('湖蓝', 'Lake Blue', '#1F79E5'),
    _co('蓝色', 'Blue', '#002E96'),
    _co('花生棕', 'Peanut Brown', '#875718'),
    _co('灰色', 'Gray', '#ADB1B2'),
    _co('深灰', 'Dark Gray', '#515151'),
    _co('黑色', 'Black', '#000000'),
    ],
    'PETG Translucent': [
    _co('半透粉', 'Translucent Pink', '#F9C1BD'),
    _co('半透紫', 'Translucent Purple', '#D6ABFF'),
    _co('半透橙', 'Translucent Orange', '#FF911A'),
    _co('半透棕', 'Translucent Brown', '#C9A381'),
    _co('半透水鸭绿', 'Translucent Teal', '#77EDD7'),
    _co('半透浅蓝', 'Translucent Light Blue', '#61B0FF'),
    _co('半透橄榄', 'Translucent Olive', '#748C45'),
    _co('半透灰', 'Translucent Gray', '#8E8E8E'),
    ],
    'PETG-CF': [
    _co('砖红色', 'Brick Red', '#9F332A'),
    _co('紫罗兰紫', 'Violet Purple', '#583061'),
    _co('靛蓝色', 'Indigo Blue', '#324585'),
    _co('孔雀石绿', 'Malachite Green', '#16B08E'),
    _co('黑色', 'Black', '#000000'),
    _co('钛灰色', 'Titan Gray', '#565656'),
    ],
    'PLA Aero': [
    _co('白色', 'White', '#F0EFE9'),
    _co('黑色', 'Black', '#1B1B1B'),
    ],
    'PLA Basic': [
    _co('玉石白', 'Jade White', '#FFFFFF'),
    _co('米色', 'Beige', '#F7E6DE'),
    _co('浅灰', 'Light Gray', '#D1D3D5'),
    _co('银色', 'Silver', '#A6A9AA'),
    _co('灰色', 'Gray', '#8E9089'),
    _co('品红', 'Magenta', '#EC008C'),
    _co('粉色', 'Pink', '#F55A74'),
    _co('热粉色', 'Hot Pink', '#F5547C'),
    _co('橙色', 'Orange', '#FF6A13'),
    _co('南瓜橙', 'Pumpkin Orange', '#FF9016'),
    _co('金色', 'Gold', '#E4BD68'),
    _co('向日葵黄', 'Sunflower Yellow', '#FEC600'),
    _co('黄色', 'Yellow', '#F4EE2A'),
    _co('亮绿色', 'Bright Green', '#BECF00'),
    _co('拓竹绿', 'Bambu Green', '#00AE42'),
    _co('槲寄生绿', 'Mistletoe Green', '#3F8E43'),
    _co('青铜色', 'Bronze', '#847D48'),
    _co('可可棕', 'Cocoa Brown', '#6F5034'),
    _co('棕色', 'Brown', '#9D432C'),
    _co('酒红色', 'Maroon Red', '#9D2235'),
    _co('红色', 'Red', '#C12E1F'),
    _co('绿松石', 'Turquoise', '#00B1B7'),
    _co('青色', 'Cyan', '#0086D6'),
    _co('蓝色', 'Blue', '#0A2989'),
    _co('钴蓝', 'Cobalt Blue', '#0056B8'),
    _co('紫色', 'Purple', '#5E43B7'),
    _co('靛紫', 'Indigo Purple', '#482960'),
    _co('蓝灰', 'Blue Grey', '#5B6579'),
    _co('深灰', 'Dark Gray', '#545454'),
    _co('黑色', 'Black', '#000000'),
    ],
    'PLA Basic Gradient': [
    _co('北极低语', 'Arctic Whisper', '#FFFFFF'),
    _co('海洋渐变草原', 'Ocean to Meadow', '#54FF9B'),
    _co('棉花糖云', 'Cotton Candy Cloud', '#E7C1D5'),
    _co('蓝莓泡泡糖', 'Blueberry Bubblegum', '#6FCAEF'),
    _co('薄荷青柠', 'Mint Lime', '#4EC939'),
    _co('日光微风', 'Solar Breeze', '#FFFFFF'),
    _co('粉柑橘', 'Pink Citrus', '#F78F77'),
    _co('暮色辉光', 'Dusk Glare', '#ED9558'),
    ],
    'PLA Galaxy': [
    _co('棕色（金闪棕底）', 'Brown (Brown base with gold shimmer)', '#684A43'),
    _co('绿色（金闪绿底）', 'Green (Green base with gold shimmer)', '#3B665E'),
    _co('星云（深蓝底绿闪）', 'Nebulae (Deep blue base with green shimmer)', '#424379'),
    _co('紫色（蓝闪紫底）', 'Purple (Purple base with blue shimmer)', '#594177'),
    ],
    'PLA Glow': [
    _co('夜光绿', 'Glow Green', '#A1FFAC'),
    _co('夜光黄', 'Glow Yellow', '#F8FF80'),
    _co('夜光粉', 'Glow Pink', '#F17B8F'),
    _co('夜光蓝', 'Glow Blue', '#7AC0E9'),
    _co('夜光橙', 'Glow Orange', '#FF9D5B'),
    ],
    'PLA Marble': [
    _co('白大理石', 'White Marble', '#F7F3F0'),
    _co('红花岗', 'Red Granite', '#AD4E38'),
    ],
    'PLA Matte': [
    _co('象牙白', 'Ivory White', '#FFFFFF'),
    _co('骨白', 'Bone White', '#CBC6B8'),
    _co('沙漠黄', 'Desert Tan', '#E8DBB7'),
    _co('拿铁棕', 'Latte Brown', '#D3B7A7'),
    _co('焦糖', 'Caramel', '#AE835B'),
    _co('赤陶', 'Terracotta', '#B15533'),
    _co('深棕', 'Dark Brown', '#7D6556'),
    _co('黑巧克力', 'Dark Chocolate', '#4D3324'),
    _co('丁香紫', 'Lilac Purple', '#AE96D4'),
    _co('樱花粉', 'Sakura Pink', '#E8AFCF'),
    _co('柑橘橙', 'Mandarin Orange', '#F99963'),
    _co('柠檬黄', 'Lemon Yellow', '#F7D959'),
    _co('李子紫', 'Plum', '#950051'),
    _co('猩红', 'Scarlet Red', '#DE4343'),
    _co('深红', 'Dark Red', '#BB3D43'),
    _co('深绿', 'Dark Green', '#68724D'),
    _co('草绿', 'Grass Green', '#61C680'),
    _co('苹果绿', 'Apple Green', '#C2E189'),
    _co('冰蓝', 'Ice Blue', '#A3D8E1'),
    _co('天蓝', 'Sky Blue', '#56B7E6'),
    _co('海军蓝', 'Marine Blue', '#0078BF'),
    _co('深蓝', 'Dark Blue', '#042F56'),
    _co('烟灰', 'Ash Gray', '#9B9EA0'),
    _co('水泥灰', 'Nardo Gray', '#757575'),
    _co('炭黑', 'Charcoal', '#000000'),
    ],
    'PLA Metal': [
    _co('金属铱金', 'Iridium Gold Metallic', '#B39B84'),
    _co('金属铜棕', 'Copper Brown Metallic', '#AA6443'),
    _co('金属氧化绿', 'Oxide Green Metallic', '#1D7C6A'),
    _co('金属钴蓝', 'Cobalt Blue Metallic', '#39699E'),
    _co('金属铁灰', 'Iron Gray Metallic', '#43403D'),
    ],
    'PLA Pure': [
    _co('纯白色', 'Pure White', '#FFFFFF'),
    _co('纯黑（Absolute Balck，官方拼写）', 'Absolute Balck', '#000000'),
    _co('婴儿蓝', 'Baby Blue', '#A4DBE8'),
    _co('奶粉色', 'Milky Pink', '#F7CED7'),
    _co('杏色', 'Apricot', '#FFB673'),
    ],
    'PLA Silk Multi-Color': [
    {"name": '破晓光辉', "en": 'Dawn Radiance', "hex": '#AF70B1', "official": False, "hex2": '#73CCB8', "hex3": '#CAA769'},
    {"name": '极光紫', "en": 'Aurora Purple', "hex": '#4F4AA9', "official": False, "hex2": '#0A69C4', "hex3": '#803697'},
    {"name": '南海滩', "en": 'South Beach', "hex": '#F272A3', "official": False, "hex2": '#0C8F8B', "hex3": '#AF7B9C'},
    {"name": '幻影蓝', "en": 'Phantom Blue', "hex": '#000000', "official": False, "hex2": '#00629B', "hex3": '#CCCCCC'},
    {"name": '神秘品红', "en": 'Mystic Magenta', "hex": '#39913F', "official": False, "hex2": '#720062', "hex3": '#CCCCCC'},
    {"name": '霓虹之城', "en": 'Neon City', "hex": '#0046BA', "official": False, "hex2": '#BA22A3', "hex3": '#CCCCCC'},
    {"name": '午夜烈焰', "en": 'Midnight Blaze', "hex": '#0046BA', "official": False, "hex2": '#7C1B49', "hex3": '#CCCCCC'},
    {"name": '鎏金玫瑰', "en": 'Gilded Rose', "hex": '#FE9325', "official": False, "hex2": '#E74175', "hex3": '#CCCCCC'},
    {"name": '蓝色夏威夷', "en": 'Blue Hawaii', "hex": '#60A3E8', "official": False, "hex2": '#4DE4A0', "hex3": '#CCCCCC'},
    {"name": '丝绒月蚀', "en": 'Velvet Eclipse', "hex": '#000000', "official": False, "hex2": '#A34342', "hex3": '#CCCCCC'},
    ],
    'PLA Silk+': [
    _co('白色', 'White', '#FFFFFF'),
    _co('银色', 'Silver', '#C8C8C8'),
    _co('香槟色', 'Champagne', '#F3CFB2'),
    _co('粉色', 'Pink', '#F7ADA6'),
    _co('玫瑰金', 'Rose Gold', '#BA9594'),
    _co('糖果红', 'Candy Red', '#D02727'),
    _co('金色', 'Gold', '#F4A925'),
    _co('薄荷绿', 'Mint', '#96DCB9'),
    _co('糖果绿', 'Candy Green', '#018814'),
    _co('婴儿蓝', 'Baby Blue', '#A8C6EE'),
    _co('蓝色', 'Blue', '#008BDA'),
    _co('紫色', 'Purple', '#8671CB'),
    _co('钛灰色', 'Titan Gray', '#5F6367'),
    ],
    'PLA Sparkle': [
    _co('经典金闪粉', 'Classic Gold Sparkle', '#CEA629'),
    _co('石板灰闪粉', 'Slate Gray Sparkle', '#8E9089'),
    _co('绯红闪粉', 'Crimson Red Sparkle', '#792B36'),
    _co('皇家紫闪粉', 'Royal Purple Sparkle', '#483D8B'),
    _co('高山绿闪粉', 'Alpine Green Sparkle', '#3F5443'),
    _co('黑曜石闪粉', 'Onyx Black Sparkle', '#2D2B28'),
    ],
    'PLA Tough': [
    _co('白色', 'White', '#FFFFFF'),
    _co('灰色', 'Gray', '#AFB1AE'),
    _co('黑色', 'Black', '#000000'),
    _co('银色', 'Silver', '#959698'),
    _co('黄色', 'Yellow', '#F4D53F'),
    _co('青色', 'Cyan', '#009BD8'),
    _co('橙色', 'Orange', '#DC3A27'),
    ],
    'PLA Translucent': [
    _co('水鸭绿', 'Teal', '#009FA1'),
    _co('浅玉色', 'Light Jade', '#96D8AF'),
    _co('蓝色', 'Blue', '#0047BB'),
    _co('柔黄色', 'Mellow Yellow', '#F5DBAB'),
    _co('紫色', 'Purple', '#8344B0'),
    _co('樱桃粉', 'Cherry Pink', '#F5B6CD'),
    _co('橙色', 'Orange', '#F74E02'),
    _co('冰蓝', 'Ice Blue', '#B8CDE9'),
    _co('红色', 'Red', '#B50011'),
    _co('薰衣草紫', 'Lavender', '#B8ACD6'),
    ],
    'PLA Wood': [
    _co('白橡木', 'White Oak', '#D6CCA3'),
    _co('赭黄色', 'Ochre Yellow', '#C98935'),
    _co('陶土棕', 'Clay Brown', '#995F11'),
    _co('经典桦木', 'Classic Birch', '#918669'),
    _co('玫瑰木色', 'Rosewood', '#4C241C'),
    _co('黑胡桃', 'Black Walnut', '#4F3F24'),
    ],
    'PLA-CF': [
    _co('勃艮第红', 'Burgundy Red', '#951E23'),
    _co('鸢尾紫', 'Iris Purple', '#69398E'),
    _co('抹茶绿', 'Matcha Green', '#5C9748'),
    _co('牛仔蓝', 'Jeans Blue', '#6E88BC'),
    _co('宝蓝色', 'Royal Blue', '#2842AD'),
    _co('熔岩灰', 'Lava Gray', '#4D5054'),
    _co('黑色', 'Black', '#000000'),
    ],
    'PPA-CF': [
    _co('黑色', 'Black', '#000000'),
    ],
    'PPS-CF': [
    _co('黑色', 'Black', '#1F1F1F'),
    ],
    'PVA': [
    _co('透明色', 'Clear', '#F0F1A8'),
    ],
    'Support for ABS': [
    _co('本色', 'Natural', '#E8E4D8'),
    ],
    'Support for PA/PET': [
    _co('绿色', 'Green', '#C0DF16'),
    ],
    'Support for PLA': [
    _co('本色', 'Natural', '#EDE8D8'),
    ],
    'Support for PLA/PETG': [
    _co('本色', 'Nature', '#CCCCCC'),
    _co('黑色', 'Black', '#000000'),
    ],
    'TPU 85A/90A': [
    _co('黑色', 'Black', '#1C1C1C'),
    _co('白色', 'White', '#EDEDE9'),
    ],
    'TPU 95A HF': [
    _co('白色', 'White', '#FFFFFF'),
    _co('灰色', 'Gray', '#898D8D'),
    _co('黄色', 'Yellow', '#F3E600'),
    _co('蓝色', 'Blue', '#0072CE'),
    _co('红色', 'Red', '#C8102E'),
    _co('黑色', 'Black', '#101820'),
    ],
    'TPU for AMS': [
    _co('蓝色', 'Blue', '#5898DD'),
    _co('红色', 'Red', '#ED0000'),
    _co('黄色', 'Yellow', '#F9EF41'),
    _co('霓虹绿', 'Neon Green', '#90FF1A'),
    _co('白色', 'White', '#CCCCCC'),
    _co('灰色', 'Gray', '#939393'),
    _co('黑色', 'Black', '#000000'),
    ],
}

BAMBU_MATERIAL_SERIES: dict[str, list[str]] = {'PLA': ['PLA Basic', 'PLA Matte', 'PLA Pure', 'PLA Tough', 'PLA Silk+', 'PLA Silk Multi-Color', 'PLA Translucent', 'PLA Glow', 'PLA Galaxy', 'PLA Sparkle', 'PLA Metal', 'PLA Marble', 'PLA Wood', 'PLA-CF', 'PLA Aero', 'PLA Basic Gradient', 'Support for PLA'], 'PETG': ['PETG Basic', 'PETG HF', 'PETG-CF', 'PETG Translucent', 'Support for PLA/PETG'], 'ABS': ['ABS', 'ABS-GF', 'Support for ABS'], 'ASA': ['ASA', 'ASA Aero', 'ASA-CF'], 'PC': ['PC'], 'PA': ['PAHT-CF', 'PPA-CF', 'Support for PA/PET'], 'PET-CF': ['PET-CF'], 'TPU': ['TPU 95A HF', 'TPU for AMS', 'TPU 85A/90A'], 'PVA': ['PVA']}
