"""品牌配色预设（自动生成 + 人工核对，勿手改排序）。

数据来源：
- Kexcelled：kexcelled3d.com 官方商品页色名（中/英），HEX 从官方产品图取主色，为近似值；
  K5 PETG Rapid 的 HEX 直接从官方 Shopify 商品图逐色取主色（2026-09-16）
- 兰博：tyzh.com 官网产品图取主色 + 常规色人工校正，均为近似值
- 魔创：淘宝官方店（shop462851793）商品 SKU 色名 + SKU 图取主色，均为近似值
- 拓竹：store.bambulab.com 官方公布的 Hex Code Table（PLA Basic / PLA Matte / PETG Basic
  / PETG HF），这些是官方色值（official=True）
- 大简：京东/淘宝官方店在售 SKU 色名 + 官方微博展示色，HEX 为近似值
"""

def _c(name: str, en: str, hex_value: str) -> dict:
    # 该文件里的 HEX 均非官方公布色值，一律视为近似值
    return {"name": name, "en": en, "hex": hex_value, "official": False}

def _co(name: str, en: str, hex_value: str) -> dict:
    # 厂商官方公布的色值（拓竹 Hex Code Table）
    return {"name": name, "en": en, "hex": hex_value, "official": True}

KEXCELLED_K5_PLA: list[dict] = [
    _c('凯蒂粉', 'Kitty Pink', '#FBB3BA'),
    _c('暗玫瑰粉', 'Dark Rose Pink', '#683440'),
    _c('白色', 'White', '#E5E5E5'),
    _c('草绿', 'Grass Green', '#7FD530'),
    _c('橙色', 'Orange', '#FC6A17'),
    _c('粉蓝色', 'Pinkish Blue', '#2DCDCC'),
    _c('粉色', 'Pink', '#FC737F'),
    _c('肤色', 'Skin', '#F0DBCC'),
    _c('古铜', 'Copper', '#6F5033'),
    _c('骨白', 'Bone White', '#F3E4AC'),
    _c('黑色', 'Black', '#1C1C1C'),
    _c('红色', 'Red', '#D0070D'),
    _c('湖蓝', 'Lake Blue', '#2193E8'),
    _c('黄色', 'Yellow', '#FEEC03'),
    _c('灰蓝', 'Gray Blue', '#778491'),
    _c('灰色', 'Gray', '#888888'),
    _c('金色', 'Gold', '#D8AB62'),
    _c('酒红', 'Wine Red', '#5F1413'),
    _c('孔雀蓝', 'Peacock Blue', '#00949E'),
    _c('蓝色', 'Blue', '#2239A7'),
    _c('蓝紫色', 'Blue Purple', '#6226B1'),
    _c('浅紫色', 'Light Purple', '#554BBA'),
    _c('绿色', 'Green', '#1E8436'),
    _c('美式肤色', 'American Skin', '#ECD5C6'),
    _c('嫩绿', 'Peak Green', '#C4EB69'),
    _c('七分白', 'Seven White', '#E5E5E5'),
    _c('浅橙色', 'Light Orange', '#FC9319'),
    _c('浅蓝色', 'Light Blue', '#68BCF2'),
    _c('浅棕色', 'Light Brown', '#C17D3D'),
    _c('巧克力', 'Chocolate', '#4C210B'),
    _c('青碧色', 'Bluish Green', '#00BF7F'),
    _c('青色', 'Cyan', '#41E9B7'),
    _c('青铜', 'Bronze', '#816D45'),
    _c('三原色品红', 'Process Magenta', '#CE3696'),
    _c('三原色青', 'Process Cyan', '#258DDB'),
    _c('森林绿', 'Forest Green', '#0D3E29'),
    _c('深黄色', 'Dark Yellow', '#F8B00A'),
    _c('墨绿', 'Dark Green', '#004E3E'),
    _c('桃粉色', 'Peach Pink', '#F0CED8'),
    _c('天空蓝', 'Sky Blue', '#3EA6DC'),
    _c('杏仁黄', 'Almond Yellow', '#ECF59C'),
    _c('血红', 'Blood Red', '#8D0C15'),
    _c('薰衣草紫', 'Lavender purple', '#886CBF'),
    _c('银色', 'Silver', '#B9BABF'),
    _c('荧光橙', 'Fluorescent Orange', '#FF6207'),
    _c('荧光红', 'Fluorescent Red', '#FA2B6E'),
    _c('荧光黄', 'Fluorescent Yellow', '#EEFD04'),
    _c('荧光绿', 'Fluorescent Green', '#71F03F'),
    _c('紫色', 'Purple', '#B131A5'),
    _c('自然色', 'Natural', '#ECE8DF'),
    _c('棕色', 'Brown', '#7C4628'),
]

KEXCELLED_K5_PLA_MATTE: list[dict] = [
    _c('牛皮纸', 'Matte Kraft', '#BBA572'),
    _c('肤色', 'Skin', '#D9C8BA'),
    _c('薄粉色', 'Slender Pink', '#E4D6D8'),
    _c('薄荷绿', 'Mint Green', '#C4CF84'),
    _c('薄绿', 'Slender Green', '#A3C7B6'),
    _c('薄紫', 'Slender Purple', '#CFCBD7'),
    _c('宝蓝色', 'Royal blue', '#2C3867'),
    _c('冰蓝', 'Ice blue', '#9CC8E2'),
    _c('车厘子红', 'Chelsea Red', '#8D2425'),
    _c('橙红', 'Orange Red', '#D66E27'),
    _c('赤陶土', 'Matte Terracotta', '#BF9485'),
    _c('淡橘色', 'Pastel orange', '#E6A13B'),
    _c('淡绿色', 'Plastel Green', '#CAD9BF'),
    _c('淡紫', 'Lavender', '#D9D7DD'),
    _c('丁香紫', 'Lilac Purple', '#BDAEDE'),
    _c('浅黄', 'Light Yellow', '#E2DB91'),
    _c('枫炽红', 'Maple Red', '#CC2320'),
    _c('橄榄绿', 'Matte Olive Green', '#3A4A2C'),
    _c('高贵紫', 'Noble Purple', '#9380CB'),
    _c('海军蓝', 'Matte Navy', '#2C3A4D'),
    _c('消光黑', 'Matte Black', '#252626'),
    _c('消光黄', 'Matte Yellow', '#E8C812'),
    _c('灰白', 'Offwhite', '#D5CDBF'),
    _c('焦糖橙', 'Burnt Orange', '#BA6E35'),
    _c('芥末黄', 'Matte Mustard Yellow', '#C69C2E'),
    _c('芥末绿', 'Mustard Green', '#92892C'),
    _c('军绿', 'Army Green', '#343D1A'),
    _c('科技灰', 'Matte Tech Gray', '#9CA0A0'),
    _c('青碧色', 'Bluish Gray', '#407079'),
    _c('栗色', 'Maroon', '#611226'),
    _c('麦芽色', 'Matte Malt Clay', '#756347'),
    _c('明黄', 'Hot yellow', '#D5D93A'),
    _c('奶黄', 'Creamy yellow', '#E0DFC0'),
    _c('奶绿', 'Milk Green', '#D9E4CA'),
    _c('嫩青', 'Vivid Cyan', '#ABDACB'),
    _c('暖灰', 'Matte Warm Gray', '#8B8677'),
    _c('浅赤陶土', 'Light Matte Terracotta', '#CE9F97'),
    _c('浅肤色', 'Light Skin', '#E6D9D2'),
    _c('浅米白', 'Light Beige', '#CDCABE'),
    _c('浅木色', 'Light Wood', '#C4BCB2'),
    _c('浅棕色', 'Light Brown', '#846549'),
    _c('青绿', 'Green Aurora', '#26B694'),
    _c('晴蓝', 'Sunny Blue', '#A6C3DF'),
    _c('珊瑚粉', 'Coral Pink', '#EACED4'),
    _c('深棕', 'Dark Brown', '#413421'),
    _c('水蓝', 'Aqua Blue', '#C3D5DD'),
    _c('松绿', 'Pine Green', '#1A6044'),
    _c('松石绿', 'Matte Turquoise', '#47C2C7'),
    _c('桃粉色', 'Peach Pink', '#F0CED8'),
    _c('藤紫', 'Rattan Purple', '#B7A8D2'),
    _c('白色', 'White', '#DFDFDF'),
    _c('烟灰', 'Ash Gray', '#404243'),
    _c('烟熏紫', 'Ash Purple', '#715D61'),
    _c('夜岩黑', 'Nightstone black', '#2C2B2B'),
    _c('棕色', 'Brown', '#534026'),
]

KEXCELLED_K5_PETG: list[dict] = [
    _c('棕色', 'Brown', '#74361D'),
    _c('白色', 'White', '#E3E3E2'),
    _c('博世蓝绿色', 'Bosch Blue Green', '#375659'),
    _c('草绿', 'Grass Green', '#7AD13F'),
    _c('橙色', 'Orange', '#E1612A'),
    _c('杜瓦特黄色', 'Dewalt Yellow', '#F2A93F'),
    _c('粉蓝色', 'Pinkish Blue', '#8EE9ED'),
    _c('粉色', 'Pink', '#FF7E8A'),
    _c('肤色', 'Skin', '#F0E1D0'),
    _c('古铜', 'Copper', '#693B1D'),
    _c('光扩散', 'Diffuse Clear White', '#ECE6E1'),
    _c('赫拉克勒斯蓝', 'Hercules Blue', '#165A8C'),
    _c('黑色', 'Black', '#181818'),
    _c('红色', 'Red', '#F13931'),
    _c('湖蓝', 'Lake Blue', '#1A92E5'),
    _c('黄色', 'Yellow', '#FDE81E'),
    _c('灰蓝', 'Gray Blue', '#70798C'),
    _c('灰色', 'Gray', '#9F9FA3'),
    _c('金色', 'Gold', '#D39939'),
    _c('孔雀蓝', 'Peacock Blue', '#13AFDF'),
    _c('蓝色', 'Blue', '#1F2CA1'),
    _c('蓝紫色', 'Blue Purple', '#6F34AC'),
    _c('绿色', 'Green', '#33B362'),
    _c('嫩绿', 'Peak Green', '#D0E172'),
    _c('浅橙色', 'Light Orange', '#FC7A0E'),
    _c('浅紫色', 'Light Purple', '#8F76D5'),
    _c('浅棕色', 'Light Brown', '#C27321'),
    _c('巧克力', 'Chocolate', '#3F2019'),
    _c('青色', 'Cyan', '#96E6C8'),
    _c('青铜', 'Bronze', '#615439'),
    _c('深黄色', 'Dark Yellow', '#E6A514'),
    _c('墨绿', 'Dark Green', '#0A5D6B'),
    _c('透明白', 'Transparent White', '#E7E6E5'),
    _c('透明勃肯第红', 'Transparent Burgundy', '#CD111B'),
    _c('透明橙', 'Transparent Orange', '#ED9F12'),
    _c('透明粉', 'Transparent Pink', '#F5CCD4'),
    _c('透明橄榄绿', 'Transparent Olive Green', '#83981F'),
    _c('透明黑', 'Transparent Black', '#65605D'),
    _c('透明红', 'Transparent Red', '#F42F38'),
    _c('透明黄', 'Transparent Yellow', '#FDE41C'),
    _c('透明蓝', 'Transparent Blue', '#5974B9'),
    _c('透明墨绿', 'Transparent Dark Green', '#2E6C27'),
    _c('透明浅紫', 'Transparent Light Purple', '#CFB0E3'),
    _c('透明水晶绿', 'Transparent Crystal Green', '#89D0C5'),
    _c('透明丝绸蓝', 'Transparent Silk Blue', '#9DD3E3'),
    _c('透明棕', 'Transparent Brown', '#7F573F'),
    _c('透明博世蓝绿', 'Transparent Bosch Blue Green', '#1A5760'),
    _c('银色', 'Silver', '#C1C2C2'),
    _c('荧光绿', 'Fluorescent Green', '#64F44F'),
    _c('遮光白', 'Light-shielding White', '#E2E2E2'),
    _c('紫色', 'Purple', '#D848B7'),
    _c('Natural', 'Natural', '#EEE8DA'),
]

KEXCELLED_K5_PETG_MATTE: list[dict] = [
    _c('苹果绿', '', '#A9CD48'),
    _c('风趣蓝', '', '#BCC7E0'),
    _c('军绿', '', '#3B4C2E'),
    _c('黑色', 'Black', '#1E1F1F'),
    _c('温馨黄', '', '#DAC9A0'),
    _c('焦糖橙', '', '#CCAD8F'),
    _c('车厘子红', '', '#5F1C22'),
    _c('藏青色', '', '#2F353F'),
    _c('金穗黄', '', '#F2EC12'),
    _c('风韵紫', '', '#646079'),
    _c('雾霭蓝', '', '#6D7C90'),
    _c('茱萸粉', '', '#E0C0C2'),
    _c('鼠尾草绿', '', '#C4D9BE'),
    _c('暖灰', '', '#D6D2CE'),
    _c('白色', 'White', '#DCDCDC'),
    _c('肤色', 'Skin', '#F2E1CE'),
    _c('巧克力', 'Chocolate', '#63422E'),
    _c('赤陶土', '', '#DE8E75'),
    _c('炽果橙', '', '#FA792A'),
    _c('枫炽红', '', '#AF2B25'),
    _c('莫兰迪绿', '', '#244F59'),
    _c('松石绿', '', '#50C3CA'),
]

KEXCELLED_K5_PETG_RAPID: list[dict] = [
    # 独立产品线（THE K5™ PETG Rapid），20 色与普通 K5 PETG 完全不同；
    # 用户实购的「日落橙 / 星雾紫」就在这一系列（此前只录了普通版，对不上）。
    _c('奶油绿', 'Cream Green', '#E2E7B0'),
    _c('白色', 'White', '#F9F9FA'),
    _c('薄荷蓝', 'Mint Blue', '#61C9CF'),
    _c('黑色', 'Black', '#202020'),
    _c('红色', 'Red', '#F32A23'),
    _c('黄色', 'Yellow', '#FEEE26'),
    _c('灰色', 'Gray', '#A1A1A1'),
    _c('金色', 'Gold', '#D79B3D'),
    _c('金属紫', 'Metallic Purple', '#8F6AA9'),
    _c('蓝色', 'Blue', '#2829BF'),
    _c('日落橙', 'Sunset Orange', '#F5510B'),
    _c('绿色', 'Green', '#3BAA57'),
    _c('摩卡棕', 'Mocha Brown', '#6C4C36'),
    _c('柔粉', 'Soft Pink', '#CEB4AF'),
    _c('裸粉', 'Nude Pink', '#ECE2D6'),
    _c('苔藓绿', 'Moss Green', '#305B17'),
    _c('太空灰', 'Space Gray', '#A3A1A5'),
    _c('透明白', 'Clear White', '#EFEDED'),
    _c('星雾紫', 'Mist Purple', '#5C30B4'),
    _c('银色', 'Silver', '#B9B9BA'),
]

# ── 拓竹（官方 Hex Code Table，official=True）─────────────────────
BAMBU_PLA_BASIC: list[dict] = [
    _co('玉石白', 'Jade White', '#FFFFFF'),
    _co('米色', 'Beige', '#F7E6DE'),
    _co('金色', 'Gold', '#E4BD68'),
    _co('银色', 'Silver', '#A6A9AA'),
    _co('灰色', 'Gray', '#8E9089'),
    _co('青铜色', 'Bronze', '#847D48'),
    _co('棕色', 'Brown', '#9D432C'),
    _co('可可棕', 'Cocoa Brown', '#6F5034'),
    _co('酒红色', 'Maroon Red', '#9D2235'),
    _co('红色', 'Red', '#C12E1F'),
    _co('品红', 'Magenta', '#EC008C'),
    _co('粉色', 'Pink', '#F55A74'),
    _co('热粉色', 'Hot Pink', '#F5547C'),
    _co('橙色', 'Orange', '#FF6A13'),
    _co('南瓜橙', 'Pumpkin Orange', '#FF9016'),
    _co('向日葵黄', 'Sunflower Yellow', '#FEC600'),
    _co('黄色', 'Yellow', '#F4EE2A'),
    _co('亮绿色', 'Bright Green', '#BECF00'),
    _co('拓竹绿', 'Bambu Green', '#00AE42'),
    _co('槲寄生绿', 'Mistletoe Green', '#3F8E43'),
    _co('绿松石', 'Turquoise', '#00B1B7'),
    _co('青色', 'Cyan', '#0086D6'),
    _co('蓝色', 'Blue', '#0A2989'),
    _co('钴蓝', 'Cobalt Blue', '#0056B8'),
    _co('紫色', 'Purple', '#5E43B7'),
    _co('靛紫', 'Indigo Purple', '#482960'),
    _co('蓝灰', 'Blue Gray', '#5B6579'),
    _co('浅灰', 'Light Gray', '#D1D3D5'),
    _co('深灰', 'Dark Gray', '#545454'),
    _co('黑色', 'Black', '#000000'),
]

BAMBU_PLA_MATTE: list[dict] = [
    _co('象牙白', 'Ivory White', '#FFFFFF'),
    _co('骨白', 'Bone White', '#CBC6B8'),
    _co('拿铁棕', 'Latte Brown', '#D3B7A7'),
    _co('焦糖', 'Caramel', '#AE835B'),
    _co('赤陶', 'Terracotta', '#B15533'),
    _co('沙漠黄', 'Desert Tan', '#E8DBB7'),
    _co('烟灰', 'Ash Gray', '#9B9EA0'),
    _co('水泥灰', 'Nardo Gray', '#757575'),
    _co('丁香紫', 'Lilac Purple', '#AE96D4'),
    _co('樱花粉', 'Sakura Pink', '#E8AFCF'),
    _co('李子紫', 'Plum', '#950051'),
    _co('柑橘橙', 'Mandarin Orange', '#F99963'),
    _co('柠檬黄', 'Lemon Yellow', '#F7D959'),
    _co('猩红', 'Scarlet Red', '#DE4343'),
    _co('深红', 'Dark Red', '#BB3D43'),
    _co('深棕', 'Dark Brown', '#7D6556'),
    _co('黑巧克力', 'Dark Chocolate', '#4D3324'),
    _co('深绿', 'Dark Green', '#68724D'),
    _co('苹果绿', 'Apple Green', '#C2E189'),
    _co('草绿', 'Grass Green', '#61C680'),
    _co('冰蓝', 'Ice Blue', '#A3D8E1'),
    _co('天蓝', 'Sky Blue', '#56B7E6'),
    _co('海军蓝', 'Marine Blue', '#0078BF'),
    _co('深蓝', 'Dark Blue', '#042F56'),
    _co('炭黑', 'Charcoal', '#000000'),
]

BAMBU_PETG_BASIC: list[dict] = [
    _co('白色', 'White', '#FFFFFF'),
    _co('红色', 'Red', '#D6001C'),
    _co('橙色', 'Orange', '#FF671F'),
    _co('黄色', 'Yellow', '#FCE300'),
    _co('群青蓝', 'Reflex Blue', '#001489'),
    _co('宝蓝', 'Navy Blue', '#0086D6'),
    _co('雾蓝', 'Misty Blue', '#688197'),
    _co('绿色', 'Green', '#009639'),
    _co('松绿', 'Pine Green', '#034638'),
    _co('深棕', 'Dark Brown', '#4F2C1D'),
    _co('深米色', 'Dark Beige', '#DBC8B6'),
    _co('灰色', 'Gray', '#7F7E83'),
    _co('黑色', 'Black', '#000000'),
]

BAMBU_PETG_HF: list[dict] = [
    _co('白色', 'White', '#FFFFFF'),
    _co('本色', 'Nature', '#F9F7F2'),
    _co('灰色', 'Gray', '#9EA2A2'),
    _co('蓝灰', 'Blue Gray', '#688197'),
    _co('金色', 'Gold', '#B28B33'),
    _co('红色', 'Red', '#D6001C'),
    _co('橙色', 'Orange', '#FF671F'),
    _co('黄色', 'Yellow', '#FCE300'),
    _co('青柠绿', 'Lime Green', '#7CD82B'),
    _co('绿色', 'Green', '#009639'),
    _co('湖蓝', 'Lake Blue', '#0069B1'),
    _co('蓝色', 'Blue', '#001489'),
    _co('紫色', 'Purple', '#9E007E'),
    _co('黑色', 'Black', '#000000'),
]

# ── 大简（GreatSimple，中山大简科技）───────────────────────────────
# 色名取自天猫/京东官方店在售 SKU；HEX 为近似值（官方未公布色值）。
# PETG 基础系列 40 色取自天猫官方店商品页 SKU 列表截图取色（2026-09-16，
# 商品 id=944008246964）；PETG HF 先收录已确认的 9 色，全色卡待确认。
DASU_PETG_HF: list[dict] = [
    _c('黑色', 'Black', '#222325'),
    _c('白色', 'White', '#E9E9E7'),
    _c('灰色', 'Gray', '#8E9091'),
    _c('深蓝色', 'Dark Blue', '#1F3B70'),
    _c('绀紫色', 'Indigo Purple', '#45395C'),
    _c('透明色', 'Transparent', '#E3E7E2'),
    _c('透明蓝', 'Transparent Blue', '#B7D9EA'),
    _c('香芋紫', 'Taro Purple', '#A88BC4'),
    _c('樱花粉', 'Sakura Pink', '#F0B9C4'),
]

# 通用 PETG（基础系列）全 40 色，与 PETG HF 已确认 9 色共用同名色值
DASU_PETG: list[dict] = [
    _c('白色', 'White', '#E9E9E7'),
    _c('黑色', 'Black', '#222325'),
    _c('灰色', 'Gray', '#8E9091'),
    _c('天蓝色', 'Sky Blue', '#5596E3'),
    _c('橘色', 'Orange', '#FD641F'),
    _c('透明色', 'Transparent', '#E3E7E2'),
    _c('透明紫', 'Transparent Purple', '#B7B1CC'),
    _c('透明绿', 'Transparent Green', '#CBEBAF'),
    _c('透明蓝', 'Transparent Blue', '#B7D9EA'),
    _c('绿色', 'Green', '#67D548'),
    _c('松石绿', 'Turquoise', '#3AA4A9'),
    _c('苹果绿', 'Apple Green', '#A0BF45'),
    _c('青色', 'Cyan Blue', '#3776CE'),
    _c('蓝色', 'Blue', '#2147EA'),
    _c('深蓝色', 'Dark Blue', '#1F3B70'),
    _c('樱花粉', 'Sakura Pink', '#F0B9C4'),
    _c('柠檬黄', 'Lemon Yellow', '#BCBF3D'),
    _c('玫红色', 'Rose Red', '#C45A7C'),
    _c('红色', 'Red', '#C54243'),
    _c('香芋紫', 'Taro Purple', '#A88BC4'),
    _c('紫罗兰', 'Violet', '#5252A0'),
    _c('绀紫色', 'Indigo Purple', '#45395C'),
    _c('紫色', 'Purple', '#645BB1'),
    _c('肤色', 'Skin Tone', '#E8DCCF'),
    _c('暗金色', 'Dark Gold', '#6B5636'),
    _c('拿铁色', 'Latte', '#9E8F75'),
    _c('粉红色', 'Pink', '#E779A4'),
    _c('棕色', 'Brown', '#5E433D'),
    _c('青铜色', 'Bronze', '#4F482F'),
    _c('金色', 'Gold', '#9C7D4B'),
    _c('米白色', 'Off White', '#E3E3DF'),
    _c('玫紫色', 'Magenta Purple', '#A13B9D'),
    _c('桃红色', 'Peach Red', '#BD408B'),
    _c('黄色', 'Yellow', '#F2DD00'),
    _c('杏色', 'Apricot', '#C6B7BA'),
    _c('深灰色', 'Dark Gray', '#4E4E4E'),
    _c('银色', 'Silver', '#D6D6D7'),
    _c('透明粉', 'Transparent Pink', '#EBDDE3'),
    _c('薄荷蓝', 'Mint Blue', '#A8D8D8'),
    _c('蓝灰色', 'Blue Gray', '#565E68'),
]

LANBO_SERIES: dict[str, list[dict]] = {
    'PLA': [
        _c('化石灰', '', '#8A8C94'),
        _c('薄荷绿', '', '#6FCF97'),
        _c('橘色', '', '#F07818'),
        _c('紫色', '', '#8B5FBF'),
        _c('奶黄', '', '#F2DFA4'),
        _c('粉红', '', '#F39AB6'),
        _c('青色', '', '#2AA8A0'),
        _c('咖啡色', '', '#6F4A2F'),
        _c('大理石', '', '#6D6D6E'),
        _c('肤色', '', '#E8B998'),
        _c('金色', '', '#D9A441'),
        _c('本色', '', '#EDE8DC'),
        _c('仿木色', '', '#A47D67'),
        _c('蓝色', '', '#1E6FD0'),
        _c('宝石蓝', '', '#0F5BD8'),
        _c('透明色', '', '#DDEDEF'),
        _c('亮黄色', '', '#F7E00A'),
        _c('绿色', '', '#3E9B4F'),
        _c('天蓝色', '', '#4FA8E8'),
        _c('亮绿色', '', '#8CD30F'),
        _c('橙黄色', '', '#777777'),
        _c('香芋紫', '', '#B48FC8'),
        _c('黄色', '', '#F5D312'),
        _c('红色', '', '#D42A20'),
        _c('银色', '', '#C0C4C8'),
        _c('樱花粉', '', '#F2B8C6'),
        _c('灰色', '', '#8A8E93'),
        _c('海军灰', '', '#5C6B7A'),
        _c('黑灰色', '', '#3A3D40'),
        _c('科技灰', '', '#A0A4A8'),
        _c('象牙白', '', '#EFEAD8'),
        _c('白色', '', '#F2F2EE'),
        _c('黑色', '', '#262626'),
    ],
    'PLA+': [
        _c('白色', '', '#F2F2EE'),
        _c('薄荷绿', '', '#6FCF97'),
        _c('本色', '', '#EDE8DC'),
        _c('橙黄', '', '#F59B23'),
        _c('粉红', '', '#F39AB6'),
        _c('海军灰', '', '#5C6B7A'),
        _c('黑色', '', '#262626'),
        _c('红色', '', '#D42A20'),
        _c('黄色', '', '#F5D312'),
        _c('灰色', '', '#8A8E93'),
        _c('金色', '', '#D9A441'),
        _c('橘色', '', '#F07818'),
        _c('科技灰', '', '#A0A4A8'),
        _c('蓝色', '', '#1E6FD0'),
        _c('亮绿', '', '#7ED321'),
        _c('绿色', '', '#3E9B4F'),
        _c('天蓝色', '', '#4FA8E8'),
        _c('透明色', '', '#DDEDEF'),
        _c('象牙白', '', '#EFEAD8'),
        _c('银色', '', '#C0C4C8'),
        _c('樱花粉', '', '#F2B8C6'),
        _c('紫色', '', '#8B5FBF'),
        _c('棕色', '', '#8B5E3C'),
    ],
    'PLA 哑光': [
        _c('白色', '', '#F2F2EE'),
        _c('薄荷绿', '', '#6FCF97'),
        _c('橙黄', '', '#F59B23'),
        _c('海军灰', '', '#5C6B7A'),
        _c('灰色', '', '#8A8E93'),
        _c('黑色', '', '#262626'),
        _c('红色', '', '#D42A20'),
        _c('科技灰', '', '#A0A4A8'),
        _c('抹茶绿', '', '#7BA05B'),
        _c('可可棕', '', '#7A4E38'),
        _c('蓝色', '', '#1E6FD0'),
        _c('绿色', '', '#3E9B4F'),
        _c('沙漠黄', '', '#D9B37C'),
        _c('香芋紫', '', '#B48FC8'),
        _c('水泥灰', '', '#9A9A96'),
        _c('香蕉黄', '', '#F5DE4C'),
        _c('杏色', '', '#EFD9B4'),
        _c('樱花粉', '', '#F2B8C6'),
    ],
    'PLA 丝绸': [
        _c('冰翠粉', '', '#B4A0A4'),
        _c('冰翠青', '', '#A3A3A2'),
        _c('冰翠蓝', '', '#5EC0D6'),
        _c('苹果绿', '', '#A8A6A3'),
        _c('薰衣草紫', '', '#A78BDC'),
        _c('白色', '', '#F2F2EE'),
        _c('亮金色', '', '#FFC000'),
        _c('金色', '', '#D9A441'),
        _c('法老金', '', '#C08A3A'),
        _c('青铜色', '', '#B1B335'),
        _c('红铜色', '', '#BA5B30'),
        _c('桃粉色', '', '#F5C3CE'),
        _c('亮银色', '', '#A19FA6'),
        _c('银灰色', '', '#4C97CC'),
        _c('黑色', '', '#262626'),
        _c('黑灰色', '', '#3A3D40'),
        _c('红色', '', '#D42A20'),
        _c('圣诞绿', '', '#B73C33'),
        _c('宝石蓝', '', '#0F5BD8'),
    ],
    '金属色': [
        _c('极光绿', '', '#666265'),
        _c('香槟金', '', '#6B656A'),
        _c('深海蓝', '', '#625D64'),
        _c('玫瑰金', '', '#635D63'),
    ],
    '星空闪点': [
        _c('蓝紫', '', '#3F5180'),
        _c('蓝色', '', '#1E6FD0'),
        _c('绿色', '', '#3E9B4F'),
        _c('紫色', '', '#8B5FBF'),
    ],
    '夜光': [
        _c('彩虹 01', '', '#191919'),
        _c('彩虹 02', '', '#6BB438'),
        _c('彩虹 03', '', '#07AEFB'),
        _c('彩虹 04', '', '#0089F0'),
        _c('绿色', '', '#3E9B4F'),
        _c('蓝色', '', '#1E6FD0'),
    ],
    '丝绸双色': [
        _c('双色 蓝红', '', '#868389'),
        _c('双色 蓝银', '', '#1143B7'),
        _c('双色 金绿', '', '#AA7C47'),
        _c('双色 红黑', '', '#AD3A43'),
        _c('双色 黑紫', '', '#64606A'),
        _c('双色 黄绿', '', '#4F5656'),
        _c('双色 金粉', '', '#DA5A6D'),
        _c('双色 金紫', '', '#DE5139'),
        _c('双色 银黑', '', '#4F494E'),
        _c('双色 深蓝深绿', '', '#6E6974'),
        _c('双色 金红', '', '#FF484F'),
        _c('双色 蓝金', '', '#555259'),
    ],
    '丝绸三色': [
        _c('三色 红黄蓝', '', '#7742C1'),
        _c('三色 红金紫', '', '#872A7C'),
        _c('三色 红蓝绿', '', '#605D67'),
        _c('三色 黄绿紫', '', '#7A437B'),
        _c('三色 金红蓝', '', '#77747F'),
        _c('三色 金蓝红铜', '', '#934775'),
        _c('三色 金绿玫红', '', '#924F48'),
        _c('三色 蓝绿橙', '', '#6F6B77'),
        _c('三色 绿紫铜', '', '#585169'),
    ],
    '丝绸彩虹': [
        _c('彩虹 童话', '', '#DA68AA'),
        _c('彩虹 mini糖果', '', '#CE5D66'),
        _c('彩虹 芭乐', '', '#F1B895'),
        _c('彩虹 马卡龙', '', '#7C7865'),
        _c('彩虹 冰淇淋', '', '#75A8DA'),
        _c('彩虹 宇宙', '', '#7D7881'),
        _c('彩虹 糖果', '', '#7F68A4'),
        _c('彩虹 花仙子', '', '#C9E97F'),
        _c('彩虹 晚霞', '', '#9585E7'),
        _c('彩虹 黑紫', '', '#4C4850'),
        _c('彩虹 红金', '', '#D63130'),
        _c('彩虹 蓝绿', '', '#163A60'),
    ],
    '哑光双色': [
        _c('双色 粉绿', '', '#989299'),
        _c('双色 黑红', '', '#684B4F'),
        _c('双色 蓝绿', '', '#69BE96'),
        _c('双色 蓝红', '', '#8F878F'),
        _c('双色 黄绿', '', '#86D151'),
        _c('双色 橙深紫', '', '#817A85'),
        _c('双色 橙红', '', '#F84E41'),
    ],
    '哑光三色': [
        _c('三色 粉黄蓝', '', '#87C1C6'),
        _c('三色 红黄蓝', '', '#746F7B'),
        _c('三色 红蓝绿', '', '#705E6A'),
    ],
    '哑光彩虹': [
        _c('彩虹 彩虹色', '', '#7F7AA0'),
        _c('彩虹 棒棒糖', '', '#969390'),
        _c('彩虹 02', '', '#9F9EAA'),
        _c('彩虹 黄绿橙', '', '#DEB454'),
        _c('彩虹 蓝红', '', '#87B3D8'),
        _c('彩虹 红珊瑚', '', '#A87B56'),
        _c('彩虹 红白', '', '#FE5B89'),
        _c('彩虹 蓝棕白', '', '#6F6B71'),
        _c('彩虹 蓝白', '', '#4E74E3'),
        _c('彩虹 蓝绿', '', '#76DF8D'),
    ],
    'PETG': [
        _c('雾霾蓝', '', '#7C93A8'),
        _c('白色', '', '#F2F2EE'),
        _c('珠光白', '', '#EFEDE6'),
        _c('肤色', '', '#E8B998'),
        _c('草绿色', '', '#4CAF50'),
        _c('草莓红', '', '#E0453A'),
        _c('橙黄', '', '#F59B23'),
        _c('蛋黄', '', '#F0C24A'),
        _c('黑色', '', '#262626'),
        _c('红色', '', '#D42A20'),
        _c('黄色', '', '#F5D312'),
        _c('灰色', '', '#8A8E93'),
        _c('活力橙', '', '#FF7A1E'),
        _c('咖啡色', '', '#6F4A2F'),
        _c('科技灰', '', '#A0A4A8'),
        _c('克莱因蓝', '', '#0033A0'),
        _c('樱花粉', '', '#F2B8C6'),
        _c('蓝色', '', '#1E6FD0'),
        _c('亮绿', '', '#7ED321'),
        _c('绿色', '', '#3E9B4F'),
        _c('香芋紫', '', '#B48FC8'),
        _c('森林绿', '', '#1F7A3D'),
        _c('紫色', '', '#8B5FBF'),
        _c('银色', '', '#C0C4C8'),
        _c('透明色', '', '#DDEDEF'),
        _c('透明橙', '', '#F2A25C'),
        _c('透明红', '', '#E86A5E'),
    ],
    'PETG 哑光': [
        _c('樱花粉', '', '#F2B8C6'),
        _c('嫩绿', '', '#A8D977'),
        _c('浅蓝', '', '#96C5D0'),
        _c('葡萄紫', '', '#7B4B94'),
        _c('蛋黄', '', '#F0C24A'),
        _c('肤色', '', '#E8B998'),
        _c('蓝色', '', '#1E6FD0'),
        _c('中国红', '', '#C8102E'),
        _c('灰色', '', '#8A8E93'),
        _c('棕色', '', '#8B5E3C'),
        _c('绿色', '', '#3E9B4F'),
        _c('橙色', '', '#F07818'),
        _c('白色', '', '#F2F2EE'),
        _c('黑色', '', '#262626'),
    ],
}

MOCRE_PLA: list[dict] = [
    _c('白色', "", '#DEDCDD'),
    _c('浅灰色', "", '#8A8A8A'),
    _c('灰色', "", '#7A7A79'),
    _c('黑色', "", '#1E1F21'),
    _c('红色', "", '#C60D1D'),
    _c('红橙', "", '#DA2821'),
    _c('黄色', "", '#E1BE02'),
    _c('黄橙', "", '#FB5413'),
    _c('粉色', "", '#CD808E'),
    _c('绿色', "", '#016B37'),
    _c('棕绿色（青铜）', "", '#836833'),
    _c('天蓝色', "", '#147DB5'),
    _c('蓝色', "", '#052AB8'),
    _c('紫色', "", '#5F3AAE'),
    _c('紫红色', "", '#BC1172'),
    _c('浅肤色', "", '#C09B80'),
    _c('浅咖色', "", '#6A4C41'),
    _c('深棕色', "", '#6B3A28'),
    _c('红棕色', "", '#512724'),
    _c('丝绸银色', "", '#AAAAA7'),
    _c('原木色', "", '#B99981'),
    _c('胡桃木色', "", '#9E775A'),
    _c('大理石', "", '#B2B3AF'),
]

MOCRE_PLA_MATTE: list[dict] = [
    _c('奶白', "", '#BDBCBC'),
    _c('灰色', "", '#969595'),
    _c('深灰色', "", '#5D5D5D'),
    _c('黑色', "", '#343434'),
    _c('香蕉黄', "", '#CFC399'),
    _c('沙漠黄', "", '#BDAA87'),
    _c('黄色', "", '#CCB70C'),
    _c('柘黄色', "", '#D0A808'),
    _c('黄橙', "", '#E68E2A'),
    _c('粉色', "", '#C5A7AC'),
    _c('天蓝', "", '#5DA8CB'),
    _c('香芋紫', "", '#9874A9'),
    _c('消防红', "", '#C1373B'),
    _c('浅肤色', "", '#C1B3A6'),
    _c('浅卡其', "", '#958F81'),
    _c('浅咖色', "", '#8E6C47'),
    _c('苏军绿', "", '#515B3D'),
    _c('绿色', "", '#119B42'),
    _c('海军蓝', "", '#273A5A'),
    _c('红棕', "", '#773F38'),
    _c('巧克力棕', "", '#705540'),
]

MOCRE_PLA_PLUS: list[dict] = [
    _c('白色', "", '#BBBBBB'),
    _c('灰色', "", '#7C7C7A'),
    _c('黑色', "", '#232325'),
    _c('绿色', "", '#098838'),
    _c('蓝色', "", '#0B35B5'),
    _c('仿木色', "", '#C3A984'),
    _c('黄色', "", '#D2AE0A'),
    _c('红色', "", '#BF1C20'),
    _c('深棕色', "", '#64312A'),
]

MOCRE_HT_PLA: list[dict] = [
    _c('白色', "", '#C4C4C4'),
    _c('灰色', "", '#838383'),
    _c('深灰色', "", '#47464B'),
    _c('黑色', "", '#292A2C'),
    _c('浅肤色', "", '#BAA68B'),
    _c('浅咖色', "", '#9F7C5C'),
    _c('绿色', "", '#189338'),
    _c('天蓝色', "", '#419CC9'),
    _c('蓝色', "", '#0E449E'),
    _c('黄色', "", '#D6BA1B'),
]

MOCRE_PETG: list[dict] = [
    _c('透明', "", '#D4D4D3'),
    _c('白色', "", '#DBDAD8'),
    _c('正白色', "", '#D2D2D2'),
    _c('遮光白', "", '#DADADC'),
    _c('奶白色', "", '#D6D5D3'),
    _c('浅灰色', "", '#979799'),
    _c('灰色', "", '#757575'),
    _c('黑色', "", '#28292B'),
    _c('肤色', "", '#D7C5B6'),
    _c('粉色', "", '#D6AFC2'),
    _c('樱花粉', "", '#D6879A'),
    _c('洋红色', "", '#D4318C'),
    _c('天蓝色', "", '#2492C6'),
    _c('蓝色', "", '#01318C'),
    _c('藏蓝色', "", '#28355F'),
    _c('牧田蓝', "", '#056979'),
    _c('清新绿', "", '#90C3B0'),
    _c('薄荷绿', "", '#66C8C9'),
    _c('青碧色', "", '#01B89A'),
    _c('草绿', "", '#7CBE02'),
    _c('荧光绿', "", '#28BF01'),
    _c('军绿色', "", '#3C5534'),
    _c('香芋紫', "", '#AC7DC5'),
    _c('黛紫色', "", '#3E2D79'),
    _c('香蕉黄', "", '#D8C47B'),
    _c('锌黄色', "", '#F1BD11'),
    _c('荧光橙', "", '#FE5F07'),
    _c('黄橙', "", '#FB7017'),
    _c('红橙', "", '#E94824'),
    _c('消防红', "", '#B51C2E'),
    _c('红色', "", '#D41D2C'),
    _c('浅咖色', "", '#8A6143'),
    _c('棕色', "", '#693833'),
    _c('金属银', "", '#918F90'),
    _c('金属蓝灰', "", '#676E78'),
    _c('金属枪灰色', "", '#6A6A6C'),
    _c('金属青铜', "", '#83723E'),
    _c('金属黄铜', "", '#9B734F'),
    _c('金属古铜', "", '#814431'),
    _c('金属红铜', "", '#924A3B'),
    _c('金属紫', "", '#7C5584'),
    _c('金属蓝色', "", '#4D708B'),
    _c('金属绿色', "", '#3F665F'),
]

MOCRE_PETG_MATTE: list[dict] = [
    _c('奶白色', "", '#BDBDBA'),
    _c('浅灰色', "", '#979691'),
    _c('灰色', "", '#7A7A7A'),
    _c('深灰色', "", '#58585A'),
    _c('黑色', "", '#363636'),
    _c('卡其色', "", '#A58B7C'),
    _c('香蕉黄', "", '#CFC399'),
    _c('沙漠黄', "", '#B39B7A'),
    _c('锌黄', "", '#D9B107'),
    _c('粉色', "", '#BF9DAD'),
    _c('浅肤色', "", '#C1B3A6'),
    _c('清新绿', "", '#8FBEA2'),
    _c('薄荷绿', "", '#68BAB4'),
    _c('嫩芽绿', "", '#96B410'),
    _c('草绿', "", '#83B909'),
    _c('军绿', "", '#4A5942'),
    _c('苏军绿', "", '#4E563B'),
    _c('橄榄绿', "", '#394133'),
    _c('消防红', "", '#AC1E2C'),
    _c('天蓝', "", '#44A0C1'),
    _c('牧田蓝', "", '#165966'),
    _c('黄橙', "", '#D66B2C'),
    _c('丁香紫', "", '#B8A6BE'),
    _c('香芋紫', "", '#8F769F'),
    _c('长春花蓝', "", '#5C4899'),
    _c('克莱因蓝', "", '#1D2780'),
    _c('浅咖色', "", '#876245'),
    _c('棕色', "", '#6B3D34'),
]

MOCRE_ASA: list[dict] = [
    _c('白色', "", '#C9C9C9'),
    _c('本色', "", '#CBC7BC'),
    _c('灰色', "", '#808080'),
    _c('黑色', "", '#282828'),
    _c('锌黄', "", '#EABB3B'),
    _c('黄橙', "", '#DA782F'),
    _c('红色', "", '#CE2B2C'),
    _c('绿色', "", '#2A8D3B'),
    _c('蓝色', "", '#0F60AC'),
]

MOCRE_ABS: list[dict] = [
    _c('白色', "", '#C1C1C1'),
    _c('奶白', "", '#D2CFCA'),
    _c('本色', "", '#BDB9B0'),
    _c('灰色', "", '#848380'),
    _c('黑色', "", '#28292B'),
    _c('锌黄', "", '#DEB817'),
    _c('橙色', "", '#FE661A'),
    _c('红色', "", '#EC2026'),
    _c('蓝色', "", '#0A6ADD'),
]

BRAND_COLOR_SERIES_EXTRA: dict[str, dict[str, list[dict]]] = {
    "Kexcelled": {
        "K5 PLA": KEXCELLED_K5_PLA,
        "K5 PLA 哑光": KEXCELLED_K5_PLA_MATTE,
        "K5 PETG": KEXCELLED_K5_PETG,
        "K5 PETG 哑光": KEXCELLED_K5_PETG_MATTE,
        "K5 PETG Rapid": KEXCELLED_K5_PETG_RAPID,
    },
    "拓竹": {
        "PLA Basic": BAMBU_PLA_BASIC,
        "PLA Matte": BAMBU_PLA_MATTE,
        "PETG Basic": BAMBU_PETG_BASIC,
        "PETG HF": BAMBU_PETG_HF,
    },
    "大简": {
        "PETG": DASU_PETG,
        "PETG HF": DASU_PETG_HF,
    },
    "兰博": LANBO_SERIES,
    "魔创": {
        "PLA": MOCRE_PLA,
        "PLA 哑光": MOCRE_PLA_MATTE,
        "PLA+": MOCRE_PLA_PLUS,
        "HT-PLA": MOCRE_HT_PLA,
        "PETG": MOCRE_PETG,
        "PETG 哑光": MOCRE_PETG_MATTE,
        "ASA": MOCRE_ASA,
        "ABS": MOCRE_ABS,
    },
}

MATERIAL_COLOR_SERIES_EXTRA: dict[str, list[str]] = {
    "PLA": [
        "K5 PLA", "K5 PLA 哑光",
        "PLA Basic", "PLA Matte",
        "PLA", "PLA+", "PLA 哑光", "PLA 丝绸", "金属色", "星空闪点", "夜光",
        "丝绸双色", "丝绸三色", "丝绸彩虹", "哑光双色", "哑光三色", "哑光彩虹",
        "HT-PLA",
    ],
    "PETG": ["PETG", "PETG 哑光", "K5 PETG", "K5 PETG 哑光", "K5 PETG Rapid",
             "PETG Basic", "PETG HF"],
    "ASA": ["ASA"],
    "ABS": ["ABS"],
}
